<a href="https://colab.research.google.com/github/ShoaibSheriff/Computer-Vision/blob/master/Action%20Spotting/Action_Spot_LSTM_Drink.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt

import torch.optim as optim
from torch.autograd import Variable
import torchvision.transforms as transforms

import torch
import torch.nn as nn

# import tensorflow as tf

from pprint import pprint

%pylab inline
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [9]:
import torchvision.models as models

resnet = models.resnet34(pretrained=True)
# rs = nn.Sequential(*list(resnet50.children())[:-1])
encoder = nn.Sequential(resnet, nn.Sequential(nn.Linear(1000, 96)))
encoder.eval()

import copy
gpu_dtype = torch.cuda.FloatTensor

encoder_gpu = copy.deepcopy(encoder)
encoder_gpu = encoder_gpu.cuda()
encoder_gpu.eval()

Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /root/.cache/torch/checkpoints/resnet34-333f7ec4.pth
100%|██████████| 83.3M/83.3M [00:00<00:00, 334MB/s]


Sequential(
  (0): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_runnin

In [0]:
import glob, os
os.chdir("/content/drive/My Drive/CSE 527/Project/1fps/ava/frames/")
train_ids = []
for file in glob.glob("*.mp4"):
    train_ids.append(file[:-4])
# print(train_ids)

In [0]:
df_search_seq = pd.read_csv(r"/content/drive/My Drive/CSE 527/Project/1fps/ava/ava-human-searches_anno.csv")
df_search_seq

search-id  step-id        time     video-id target-action
0               0        0  849.623600  Ag-pXiLrd48   clink glass
1               0        1  852.323675  Ag-pXiLrd48   clink glass
2               0        2  855.023750  Ag-pXiLrd48   clink glass
3               0        3  850.523625  Ag-pXiLrd48   clink glass
4               0        4  853.223700  Ag-pXiLrd48   clink glass
...           ...      ...         ...          ...           ...
893476       3987       56  726.326631  mfsbYdLx9wE         write
893477       3987       57  728.126697  mfsbYdLx9wE         write
893478       3987       58  732.626862  mfsbYdLx9wE         write
893479       3987       59  741.627192  mfsbYdLx9wE         write
893480       3987       60  744.327291  mfsbYdLx9wE         write

[893481 rows x 5 columns]

In [0]:
df_drink = df_search_seq.loc[((df_search_seq['target-action'] == 'drink') & (df_search_seq['video-id'].isin(train_ids)))]

In [0]:
searchids = df_drink.groupby(['search-id']).agg(['count']).sort_values(by = [('time', 'count')], ascending=False).reset_index()['search-id'].to_list()[2:]
data = []

for searchid in searchids:
  # print(searchid)
  df_search = df_drink.loc[(df_drink['search-id'] == searchid)].sort_values(['step-id'])

  video_id = df_search.loc[(df_search['step-id'] == 0)]['video-id'].to_list()[0]
  # print(video_id)
  input_ts = df_search['time'].to_list()
  if (len(input_ts) < 8 or len(input_ts) > 1200):
    continue
  temp = input_ts[1:]
  temp.append(input_ts[-1])
  jumps = [i-j for i, j in zip(temp, input_ts)]

  video_f = '/content/drive/My Drive/CSE 527/Project/1fps/ava/videos/'+video_id+'.mp4'
  
  sample = {'video': video_f, 'input':input_ts, 'output':jumps}
  # print(input_ts)
  # print(jumps)self.hidden
  data.append(sample)

In [0]:
from tqdm import tqdm

def generate_batches(instances, batch_size):
    """
    Generates and returns batch of tensorized instances in a chunk of batch_size.
    """

    def chunk(items, num):
        return [items[index:index+num] for index in range(0, len(items), num)]
    batches_of_instances = chunk(instances, batch_size)

    batches = []
    for batch_of_instances in tqdm(batches_of_instances):

        num_steps = [len(instance["input"])
                         for instance in batch_of_instances]
        max_steps = max(num_steps)

        count = min(batch_size, len(batch_of_instances))
        batch = {"input_seq": np.full((count, max_steps), -1, dtype=np.float32),
                 "output_steps": np.full((count, max_steps), -1, dtype=np.float32)}

        batch["video_path"] = np.full((count), "", dtype=object)

        for batch_index, instance in enumerate(batch_of_instances):
            num_tokens = len(instance["input"])

            inputs = np.array(instance["input"])
            batch["input_seq"][batch_index][:num_tokens] = inputs

            pos_inputs = np.array(instance["output"])
            batch["output_steps"][batch_index][:num_tokens] = pos_inputs

            # print(batch["video_path"].shape)
            batch["video_path"][batch_index] = instance["video"]

        batches.append(batch)
        # print('\n' + str(len(batches)))

    return batches

batches = generate_batches(data, 4)

100%|██████████| 61/61 [00:00<00:00, 4066.83it/s]


In [0]:
def train(model, optimizer, train_batches, num_epochs):

    train_batch_steps = [batch_inputs.pop("output_steps") for batch_inputs in train_batches]
    model.train()

    for epoch in range(num_epochs):
        print(f"\nEpoch{epoch}")

        epoch_loss = 0
        generator_tqdm = tqdm(list(zip(train_batches, train_batch_steps)))
        for batch_inputs, batch_steps in generator_tqdm:
            # with tf.GradientTape() as tape:
              ret = model(**batch_inputs, training=True)
              preds = ret['preds']
              slens = ret['seq_lens']
              mask = ret['mask']
              # print('in train')
              # print(preds.shape)
              # print(batch_steps.shape)
              # print(mask.shape)
              # print('mask', mask)
              losses = torch.nn.SmoothL1Loss( reduction = 'none')(preds, torch.from_numpy(batch_steps))
              # """.cuda()""")
              # print(losses)

              real_loss = torch.mul(losses, torch.from_numpy(mask))
              '''.cuda())'''
              # print('real_loss', real_loss)

              loss_val = torch.sum(real_loss)/ np.sum(mask)
              # print('loss', loss_val.data.item())

              epoch_loss += loss_val
              optimizer.zero_grad()
              loss_val.backward()
              optimizer.step()
              print('cuda memory', torch.cuda.memory_allocated())

        epoch_loss = epoch_loss / len(train_batches)
        print(f"Train loss for epoch: {epoch_loss}")
        torch.save(model.state_dict(), "/content/drive/My Drive/CSE 527/Project/model"+str(epoch)+'.v5.fltr.drp.h5')


In [0]:
class LSTMTSearch(nn.Module):

    def __init__(self):
        super(LSTMTSearch, self).__init__()

        self.hidden_size = 128
        self.batch_size = 4

        self.encoder = encoder_gpu
        # self.encoder = encoder
        self.lstm = nn.LSTM(batch_first = True, input_size = 97, hidden_size = self.hidden_size, dropout = 0.25, num_layers = 2)
        self.linear = nn.Linear(self.hidden_size, 1)

    def get_init_hidden_states(self):
        return (torch.zeros(2, self.batch_size, self.hidden_size),
                torch.zeros(2, self.batch_size, self.hidden_size))

    def forward(self, input_seq, video_path, training):

        # print(input_seq[0])
        # print(video_path[0])

        self.lstm.hidden = self.get_init_hidden_states()

        batch_ips = None
        seq_lengths = np.zeros((len(video_path)))

        for idx, video in enumerate(video_path):
          print('cuda memory', torch.cuda.memory_allocated())
          cap = cv2.VideoCapture(video)

          images = None
          # print(len(input_seq[idx]))
          slen = 0
          to_add = 0

          for ts in input_seq[idx]:
            
            if ts > -1:
              # print(ts)

              slen += 1

              cap.set(cv2.CAP_PROP_POS_MSEC, (904+ts)*1000) 
              _, frame = cap.read()
              # print(video)
              # plt.imshow(frame)

              train_transforms = transforms.Compose([
              transforms.ToPILImage(),
              transforms.Resize(70),
              transforms.CenterCrop(64),
              transforms.ToTensor(),
              transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
              ])
            
              frame2 = train_transforms(frame).cuda()
              frame2.requires_grad=False

              # plt.imshow(frame2)
              # plt.show()

              if images is None:
                images = frame2.unsqueeze(0)
              else:
                images = torch.cat((images, frame2.unsqueeze(0)), dim=0)

              # del frame2
            else:
              to_add += 1
            #     images = torch.cat((images, zeros), dim=0)
          # print(images.shape)

          seq_lengths[idx] = slen
          # print('actual sequence length', slen)

          activations = self.encoder(images).cpu()
          # print('after image encode ', activations.shape)

          # print('cuda memory', torch.cuda.memory_allocated())

          zeros_to_pad = torch.zeros([to_add, 96], dtype=torch.float32)
          """.cuda()"""
          padded_activations = torch.cat((activations, zeros_to_pad), dim=0)
          # print('after padding', padded_activations.shape)

          # print(torch.from_numpy(input_seq[idx]).unsqueeze(1).shape)

          padded_activations = torch.cat((padded_activations, torch.from_numpy(input_seq[idx]).unsqueeze(1)), dim = 1)
          """.cuda()"""
          # ), dim = 1)
          # print('after add timestamp ', padded_activations.shape)

          if batch_ips is None:
            batch_ips = padded_activations.unsqueeze(0)
          else:
            batch_ips = torch.cat((batch_ips, padded_activations.unsqueeze(0)), dim=0)

            # del padded_activations
            # del activations
            # del images
            # del zeros_to_pad
            # torch.cuda.empty_cache()

        print(batch_ips.shape)
        # print(seq_lengths)

        padded_batch_ips = torch.nn.utils.rnn.pack_padded_sequence(batch_ips, seq_lengths, batch_first=True)

        output, (h_n, c_n) = self.lstm(padded_batch_ips)
        # output1, _ = torch.nn.utils.rnn.pad_packed_sequence(output, batch_first=True)
        output2, _ = torch.nn.utils.rnn.pad_packed_sequence(output, batch_first=True)
        # print('lstm out', output2.shape)
        # print(h_n.shape)
        # print(c_n.shape)

        # # preds1 = self.linear(output1.view(-1, output1.size(2)))
        # # print('preds', preds1.shape)

        preds2 = self.linear(output2)
        # print('preds', preds2.shape)

        ret = {}
        ret['preds'] = preds2.squeeze()
        ret['seq_lens'] = seq_lengths
        ret['mask'] = input_seq > -1

        return ret
# model = LSTMTSearch()
# train(model, optim.Adam(model.parameters(), lr=0.0001), batches, 10)

In [0]:
model = LSTMTSearch()
train(model, optim.Adam(model.parameters(), lr=0.0001), batches, 20)

  0%|          | 0/61 [00:00<?, ?it/s]


Epoch0
cuda memory 88635904
cuda memory 3234025984
cuda memory 6086322688
cuda memory 8932459008
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [05:34<5:34:22, 334.38s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060686848
cuda memory 5757376512
cuda memory 8454434816
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [11:59<5:43:51, 349.69s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [16:57<5:22:56, 334.08s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [20:06<4:36:07, 290.66s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [22:33<3:50:51, 247.34s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [23:39<2:57:06, 193.20s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [24:40<2:18:02, 153.37s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [26:44<2:07:51, 144.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [28:45<1:59:12, 137.55s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [31:42<2:06:54, 149.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [35:17<2:20:54, 169.08s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [38:08<2:18:25, 169.50s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [38:59<1:47:19, 134.15s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [40:46<1:38:41, 125.99s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [42:59<1:38:10, 128.04s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [45:11<1:36:59, 129.32s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [47:19<1:34:24, 128.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [48:37<1:21:22, 113.56s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [51:33<1:32:35, 132.28s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [53:31<1:27:31, 128.08s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [54:33<1:12:09, 108.25s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [55:42<1:02:44, 96.52s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [56:38<53:26, 84.37s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [58:47<1:00:17, 97.77s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [1:00:45<1:02:14, 103.75s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [1:02:14<57:54, 99.28s/it]   

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [1:02:36<43:07, 76.10s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:03:33<38:38, 70.25s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:04:18<33:27, 62.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:04:38<25:50, 50.01s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:05:32<25:38, 51.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:06:24<24:50, 51.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:06:58<21:36, 46.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:07:38<19:51, 44.15s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:08:27<19:49, 45.75s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:09:08<18:31, 44.45s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:09:41<16:22, 40.93s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:10:24<15:55, 41.53s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:10:53<13:52, 37.86s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:11:05<10:29, 29.98s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:11:24<08:52, 26.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:11:49<08:15, 26.09s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:12:18<08:09, 27.17s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:12:49<08:02, 28.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:12:57<05:53, 22.11s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552
torch.Size([4, 70, 97])


 75%|███████▌  | 46/61 [1:13:17<05:20, 21.37s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:13:49<05:45, 24.70s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:14:01<04:31, 20.86s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:14:08<03:19, 16.64s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:14:20<02:46, 15.17s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:14:37<02:38, 15.83s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:14:59<02:40, 17.79s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:15:13<02:12, 16.57s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:15:24<01:44, 14.93s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:15:30<01:14, 12.35s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:15:38<00:55, 11.05s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:15:41<00:34,  8.65s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:16:01<00:35, 11.85s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:16:03<00:17,  8.93s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:16:12<00:08,  8.88s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:16:17<00:00,  7.74s/it]

torch.Size([4, 9, 97])
cuda memory 358729728


Train loss for epoch: 5.864429473876953


  0%|          | 0/61 [00:00<?, ?it/s]


Epoch1
cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:52<3:52:20, 232.35s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [10:01<4:28:41, 273.25s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [15:00<4:31:43, 281.09s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [18:05<3:59:39, 252.27s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:30<3:25:23, 220.06s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [21:35<2:39:10, 173.65s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [22:34<2:05:14, 139.15s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [24:38<1:58:54, 134.60s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [26:36<1:52:29, 129.80s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [29:23<1:59:41, 140.81s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [32:55<2:15:11, 162.22s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [35:38<2:12:41, 162.47s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [36:20<1:41:05, 126.36s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [38:05<1:33:59, 119.98s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [40:18<1:34:53, 123.76s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [42:31<1:34:49, 126.44s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [44:39<1:33:12, 127.11s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [46:31<1:27:44, 122.44s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [49:27<1:37:03, 138.65s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [51:23<1:30:02, 131.78s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [52:24<1:13:44, 110.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [53:05<58:20, 89.75s/it]   

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [54:01<50:27, 79.66s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [56:11<58:21, 94.63s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [58:07<1:00:37, 101.05s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [59:37<56:54, 97.57s/it]   

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [59:59<42:28, 74.94s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:00:56<38:14, 69.53s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:01:41<33:09, 62.18s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:02:01<25:37, 49.60s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:02:57<25:45, 51.52s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:03:46<24:32, 50.78s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:04:20<21:25, 45.92s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:04:58<19:35, 43.55s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:05:42<18:55, 43.66s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:06:30<18:44, 44.99s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:07:03<16:31, 41.32s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:07:41<15:27, 40.34s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:08:14<13:59, 38.18s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:08:26<10:35, 30.26s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:08:53<09:44, 29.22s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:09:18<08:48, 27.84s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:09:47<08:31, 28.40s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:10:15<08:00, 28.24s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:10:21<05:44, 21.54s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552


 75%|███████▌  | 46/61 [1:10:45<05:32, 22.16s/it]

torch.Size([4, 70, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:11:18<05:58, 25.62s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:11:30<04:39, 21.49s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:11:37<03:25, 17.11s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:11:49<02:52, 15.65s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:12:07<02:41, 16.20s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:12:28<02:38, 17.65s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:12:42<02:11, 16.44s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:12:52<01:41, 14.54s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:12:57<01:11, 11.91s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:13:05<00:52, 10.48s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:13:11<00:36,  9.20s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:13:30<00:36, 12.11s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:13:32<00:18,  9.11s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:13:40<00:08,  8.98s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:13:47<00:00,  8.28s/it]

torch.Size([4, 9, 97])
cuda memory 358729728
Train loss for epoch: 5.669723987579346



  0%|          | 0/61 [00:00<?, ?it/s]


Epoch2
cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:55<3:55:44, 235.75s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [10:04<4:31:05, 275.69s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [14:57<4:31:21, 280.71s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [18:02<3:59:33, 252.16s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:26<3:25:04, 219.73s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [21:33<2:39:28, 173.98s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [22:33<2:05:35, 139.54s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [24:38<1:59:29, 135.27s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [26:37<1:53:05, 130.50s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [29:25<2:00:22, 141.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [32:59<2:16:07, 163.35s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [35:42<2:13:22, 163.31s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [36:25<1:41:44, 127.18s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [38:11<1:34:35, 120.75s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [40:25<1:35:36, 124.71s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [42:39<1:35:42, 127.61s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [44:38<1:31:38, 124.97s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [45:58<1:19:58, 111.59s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [49:02<1:33:22, 133.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [50:59<1:27:43, 128.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [52:01<1:12:19, 108.48s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [53:02<1:01:11, 94.15s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [53:57<52:16, 82.53s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [56:07<59:37, 96.68s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [58:01<1:01:03, 101.77s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [59:29<57:05, 97.87s/it]   

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [59:52<42:40, 75.32s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:00:50<38:27, 69.93s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:01:35<33:18, 62.47s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:01:57<26:01, 50.36s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:02:54<26:10, 52.34s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:03:43<24:53, 51.51s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:04:17<21:30, 46.10s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:04:54<19:36, 43.59s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:05:46<19:54, 45.94s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:06:23<18:02, 43.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:06:56<16:04, 40.17s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:07:37<15:31, 40.50s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:08:06<13:36, 37.10s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:08:18<10:18, 29.43s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:08:44<09:27, 28.38s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:09:09<08:38, 27.31s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:09:38<08:24, 28.02s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:10:08<08:04, 28.51s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:10:14<05:47, 21.75s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552
torch.Size([4, 70, 97])


 75%|███████▌  | 46/61 [1:10:34<05:20, 21.35s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:11:07<05:48, 24.87s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:11:19<04:33, 21.01s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:11:26<03:19, 16.62s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:11:38<02:48, 15.36s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:11:55<02:39, 15.91s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:12:25<03:00, 20.03s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:12:40<02:27, 18.39s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:12:50<01:51, 15.88s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:12:58<01:22, 13.78s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:13:14<01:10, 14.17s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:13:18<00:45, 11.28s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:13:37<00:40, 13.48s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:13:41<00:21, 10.87s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:13:51<00:10, 10.47s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:13:55<00:00,  8.44s/it]

torch.Size([4, 9, 97])
cuda memory 358729728


Train loss for epoch: 5.633426666259766

Epoch3


  0%|          | 0/61 [00:00<?, ?it/s]

cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:53<3:53:44, 233.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [10:04<4:30:17, 274.86s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [15:04<4:32:55, 282.33s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [18:10<4:00:47, 253.46s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:36<3:26:24, 221.16s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [21:43<2:40:26, 175.03s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [22:42<2:06:13, 140.24s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [24:50<2:00:28, 136.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [26:49<1:53:45, 131.26s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [29:37<2:01:01, 142.38s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [33:11<2:16:35, 163.91s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [35:57<2:14:21, 164.51s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [36:40<1:42:19, 127.90s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [38:26<1:35:11, 121.53s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [40:41<1:36:04, 125.32s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [42:53<1:35:30, 127.36s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [45:04<1:34:19, 128.61s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [46:21<1:20:57, 112.98s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [49:13<1:31:34, 130.83s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [51:09<1:26:13, 126.19s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [52:09<1:11:02, 106.57s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [53:33<1:04:45, 99.62s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [54:28<54:41, 86.36s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [56:39<1:01:24, 99.58s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [58:39<1:03:30, 105.85s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [1:00:12<59:33, 102.09s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [1:00:37<44:36, 78.72s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:01:33<39:41, 72.18s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:02:18<34:01, 63.79s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:02:38<26:16, 50.85s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:03:34<26:08, 52.27s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:04:25<25:04, 51.88s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:04:58<21:36, 46.29s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:05:37<19:51, 44.11s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:06:28<19:57, 46.07s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:07:03<17:53, 42.94s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:07:37<16:00, 40.04s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:08:15<15:06, 39.43s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:08:43<13:15, 36.16s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:08:55<10:03, 28.72s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:09:18<09:04, 27.23s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:09:43<08:21, 26.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:10:12<08:10, 27.28s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:10:34<07:16, 25.65s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:10:40<05:15, 19.70s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552


 75%|███████▌  | 46/61 [1:11:01<05:03, 20.23s/it]

torch.Size([4, 70, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:11:38<05:52, 25.21s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:11:50<04:34, 21.13s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:11:57<03:22, 16.87s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:12:09<02:51, 15.62s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:12:27<02:41, 16.10s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:12:49<02:42, 18.11s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:13:03<02:14, 16.86s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:13:14<01:45, 15.11s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:13:24<01:20, 13.38s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:13:36<01:05, 13.03s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:13:41<00:42, 10.68s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:13:58<00:37, 12.53s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:14:04<00:21, 10.69s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:14:15<00:10, 10.61s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:14:18<00:00,  8.47s/it]

torch.Size([4, 9, 97])
cuda memory 358729728
Train loss for epoch: 5.582215309143066



  0%|          | 0/61 [00:00<?, ?it/s]


Epoch4
cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:50<3:50:33, 230.56s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [09:56<4:26:46, 271.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [14:54<4:29:56, 279.25s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [17:58<3:58:08, 250.68s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:22<3:24:04, 218.66s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [21:27<2:38:05, 172.47s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [22:26<2:04:35, 138.44s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [24:31<1:58:42, 134.39s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [26:30<1:52:37, 129.95s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [29:24<2:01:41, 143.18s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [32:59<2:17:10, 164.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [35:42<2:13:56, 164.01s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [36:35<1:44:38, 130.79s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [38:23<1:37:01, 123.87s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [40:39<1:37:51, 127.65s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [42:54<1:37:19, 129.76s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [44:53<1:32:51, 126.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [46:13<1:20:36, 112.48s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [49:08<1:31:53, 131.27s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [51:03<1:26:28, 126.56s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [52:05<1:11:23, 107.10s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [53:08<1:00:55, 93.74s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [54:04<52:14, 82.48s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [56:18<1:00:23, 97.93s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [58:21<1:03:18, 105.52s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [59:54<59:18, 101.67s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [1:00:17<44:15, 78.11s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:01:17<39:59, 72.70s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:02:02<34:21, 64.42s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:02:24<26:41, 51.67s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:03:21<26:36, 53.23s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:04:13<25:33, 52.88s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:04:46<21:55, 46.97s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:05:25<20:02, 44.53s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:06:10<19:23, 44.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:06:58<18:59, 45.59s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:07:32<16:51, 42.16s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:08:10<15:44, 41.05s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:08:42<14:02, 38.29s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:08:55<10:43, 30.63s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:09:20<09:37, 28.88s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:09:42<08:32, 26.95s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:10:11<08:17, 27.63s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:10:34<07:24, 26.14s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:10:40<05:20, 20.06s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552
torch.Size([4, 70, 97])


 75%|███████▌  | 46/61 [1:11:00<05:00, 20.02s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:11:36<05:47, 24.81s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:11:48<04:32, 20.97s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:11:55<03:21, 16.77s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:12:07<02:48, 15.31s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:12:24<02:39, 15.97s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:12:48<02:44, 18.26s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:13:01<02:13, 16.63s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:13:12<01:44, 14.97s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:13:19<01:15, 12.55s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:13:31<01:02, 12.43s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:13:35<00:40, 10.10s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:14:01<00:44, 14.84s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:14:10<00:26, 13.11s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:14:26<00:13, 13.87s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:14:35<00:00, 12.48s/it]

torch.Size([4, 9, 97])
cuda memory 358729728


Train loss for epoch: 5.5530571937561035

Epoch5


  0%|          | 0/61 [00:00<?, ?it/s]

cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:53<3:53:06, 233.11s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [09:58<4:28:20, 272.90s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [14:55<4:30:34, 279.91s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [18:00<3:59:01, 251.60s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:25<3:24:49, 219.46s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2198764544
cuda memory 4036698112
cuda memory 5864369152
torch.Size([4, 698, 97])


 10%|▉         | 6/61 [21:29<2:38:37, 173.04s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2159558656
cuda memory 3937275392
cuda memory 5706665984
torch.Size([4, 683, 97])


 11%|█▏        | 7/61 [22:28<2:04:47, 138.65s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2020024320
cuda memory 3649091584
cuda memory 5223763968
torch.Size([4, 630, 97])


 13%|█▎        | 8/61 [24:31<1:58:22, 134.00s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1868734464
cuda memory 3344947200
cuda memory 4819316736
torch.Size([4, 568, 97])


 15%|█▍        | 9/61 [26:29<1:51:55, 129.14s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1791664128
cuda memory 3191855104
cuda memory 4592128000
torch.Size([4, 542, 97])


 16%|█▋        | 10/61 [29:27<2:02:11, 143.76s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1733206016
cuda memory 3075559424
cuda memory 4401979392
torch.Size([4, 520, 97])


 18%|█▊        | 11/61 [33:03<2:17:50, 165.41s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1654075392
cuda memory 2946930688
cuda memory 4229341184
torch.Size([4, 490, 97])


 20%|█▉        | 12/61 [35:46<2:14:37, 164.84s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1597640704
cuda memory 2833252352
cuda memory 4056913920
torch.Size([4, 470, 97])


 21%|██▏       | 13/61 [36:37<1:44:34, 130.71s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1576587264
cuda memory 2771650560
cuda memory 3952678912
torch.Size([4, 462, 97])


 23%|██▎       | 14/61 [38:24<1:36:40, 123.42s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1521442816
cuda memory 2665760768
cuda memory 3802058752
torch.Size([4, 440, 97])


 25%|██▍       | 15/61 [40:39<1:37:18, 126.91s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1469179904
cuda memory 2576293888
cuda memory 3683407872
torch.Size([4, 421, 97])


 26%|██▌       | 16/61 [42:52<1:36:34, 128.76s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1463119872
cuda memory 2554460160
cuda memory 3637905408
torch.Size([4, 418, 97])


 28%|██▊       | 17/61 [45:02<1:34:47, 129.25s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1431248896
cuda memory 2502819840
cuda memory 3547920384
torch.Size([4, 400, 97])


 30%|██▉       | 18/61 [46:22<1:21:59, 114.40s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1378838528
cuda memory 2389006336
cuda memory 3335362560
torch.Size([4, 385, 97])


 31%|███       | 19/61 [49:17<1:32:48, 132.59s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1281839104
cuda memory 2200242176
cuda memory 3116103680
torch.Size([4, 350, 97])


 33%|███▎      | 20/61 [51:11<1:26:55, 127.20s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1254410240
cuda memory 2110881792
cuda memory 2967951360
torch.Size([4, 333, 97])


 34%|███▍      | 21/61 [52:13<1:11:45, 107.64s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1211025408
cuda memory 2057234432
cuda memory 2901016576
torch.Size([4, 321, 97])


 36%|███▌      | 22/61 [53:14<1:00:50, 93.61s/it] 

cuda memory 358729728
cuda memory 358729728
cuda memory 1193279488
cuda memory 2016444416
cuda memory 2798901248
torch.Size([4, 316, 97])


 38%|███▊      | 23/61 [54:11<52:12, 82.44s/it]  

cuda memory 358729728
cuda memory 358729728
cuda memory 1132800000
cuda memory 1906008064
cuda memory 2679721984
torch.Size([4, 293, 97])


 39%|███▉      | 24/61 [56:23<1:00:01, 97.34s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1126670336
cuda memory 1893210112
cuda memory 2622672896
torch.Size([4, 288, 97])


 41%|████      | 25/61 [58:23<1:02:30, 104.17s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1076582400
cuda memory 1773318144
cuda memory 2464921088
torch.Size([4, 271, 97])


 43%|████▎     | 26/61 [59:51<57:55, 99.31s/it]   

cuda memory 358729728
cuda memory 358729728
cuda memory 1036441600
cuda memory 1711280128
cuda memory 2386031104
torch.Size([4, 257, 97])


 44%|████▍     | 27/61 [1:00:13<43:09, 76.15s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 1029538816
cuda memory 1681295360
cuda memory 2324473344
torch.Size([4, 248, 97])


 46%|████▌     | 28/61 [1:01:10<38:38, 70.27s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 992843776
cuda memory 1609617920
cuda memory 2224409600
torch.Size([4, 238, 97])


 48%|████▊     | 29/61 [1:01:58<33:54, 63.57s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 960048128
cuda memory 1556961792
cuda memory 2134766080
torch.Size([4, 228, 97])


 49%|████▉     | 30/61 [1:02:17<26:00, 50.32s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 896669184
cuda memory 1433363456
cuda memory 1950028800
torch.Size([4, 200, 97])


 51%|█████     | 31/61 [1:03:11<25:44, 51.48s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 853189120
cuda memory 1343843840
cuda memory 1831129600
torch.Size([4, 187, 97])


 52%|█████▏    | 32/61 [1:04:04<25:02, 51.80s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 832376320
cuda memory 1303223296
cuda memory 1772677632
torch.Size([4, 178, 97])


 54%|█████▍    | 33/61 [1:04:37<21:38, 46.36s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 831839744
cuda memory 1300725248
cuda memory 1767857664
torch.Size([4, 176, 97])


 56%|█████▌    | 34/61 [1:05:16<19:50, 44.10s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 796689408
cuda memory 1229012992
cuda memory 1660814336
torch.Size([4, 164, 97])


 57%|█████▋    | 35/61 [1:06:01<19:14, 44.41s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 777582080
cuda memory 1189987840
cuda memory 1589808640
torch.Size([4, 158, 97])


 59%|█████▉    | 36/61 [1:06:47<18:37, 44.72s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 747487744
cuda memory 1131869696
cuda memory 1515334144
torch.Size([4, 145, 97])


 61%|██████    | 37/61 [1:07:20<16:31, 41.30s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 720898048
cuda memory 1069176832
cuda memory 1406615552
torch.Size([4, 133, 97])


 62%|██████▏   | 38/61 [1:07:59<15:37, 40.74s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 683305984
cuda memory 1000708096
cuda memory 1317524480
torch.Size([4, 121, 97])


 64%|██████▍   | 39/61 [1:08:29<13:41, 37.35s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 659580416
cuda memory 959026176
cuda memory 1259012608
torch.Size([4, 114, 97])


 66%|██████▌   | 40/61 [1:08:40<10:21, 29.60s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 650170368
cuda memory 934895616
cuda memory 1219620864
torch.Size([4, 109, 97])


 67%|██████▋   | 41/61 [1:09:05<09:22, 28.15s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 641919488
cuda memory 889892864
cuda memory 1137718784
torch.Size([4, 106, 97])


 69%|██████▉   | 42/61 [1:09:30<08:35, 27.14s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 600322048
cuda memory 837605376
cuda memory 1071960064
torch.Size([4, 90, 97])


 70%|███████   | 43/61 [1:09:59<08:20, 27.80s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 584376832
cuda memory 809663488
cuda memory 1025877504
torch.Size([4, 84, 97])


 72%|███████▏  | 44/61 [1:10:24<07:38, 26.95s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 568937472
cuda memory 770205696
cuda memory 963831296
torch.Size([4, 79, 97])


 74%|███████▍  | 45/61 [1:10:30<05:29, 20.62s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 549983744
cuda memory 736669184
cuda memory 923223552


 75%|███████▌  | 46/61 [1:10:54<05:23, 21.54s/it]

torch.Size([4, 70, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 528844800
cuda memory 688171520
cuda memory 839378432


 77%|███████▋  | 47/61 [1:11:26<05:47, 24.82s/it]

torch.Size([4, 64, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 508742656
cuda memory 659427328
cuda memory 804658176


 79%|███████▊  | 48/61 [1:11:38<04:32, 20.96s/it]

torch.Size([4, 56, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 499066368
cuda memory 637832192
cuda memory 771310080


 80%|████████  | 49/61 [1:11:45<03:19, 16.60s/it]

torch.Size([4, 53, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 495058432
cuda memory 619007488
cuda memory 743546368


 82%|████████▏ | 50/61 [1:11:57<02:49, 15.38s/it]

torch.Size([4, 50, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 481290240
cuda memory 600344576
cuda memory 717598720


 84%|████████▎ | 51/61 [1:12:15<02:39, 15.97s/it]

torch.Size([4, 45, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 480604160
cuda memory 594665472
cuda memory 708726784


 85%|████████▌ | 52/61 [1:12:38<02:44, 18.29s/it]

torch.Size([4, 44, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 455898112
cuda memory 550234112
cuda memory 643718144


 87%|████████▋ | 53/61 [1:12:53<02:17, 17.13s/it]

torch.Size([4, 36, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 443782144
cuda memory 525021696
cuda memory 594670080


 89%|████████▊ | 54/61 [1:13:03<01:46, 15.20s/it]

torch.Size([4, 32, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 424073216
cuda memory 489629696
cuda memory 548833280


 90%|█████████ | 55/61 [1:13:12<01:19, 13.23s/it]

torch.Size([4, 24, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 468085760
cuda memory 522968576


 92%|█████████▏| 56/61 [1:13:27<01:08, 13.63s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 414251520
cuda memory 464991232
cuda memory 516320768


 93%|█████████▎| 57/61 [1:13:32<00:45, 11.30s/it]

torch.Size([4, 20, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 411288064
cuda memory 454513664
cuda memory 496756224


 95%|█████████▌| 58/61 [1:13:54<00:43, 14.47s/it]

torch.Size([4, 19, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 398517248
cuda memory 439042048
cuda memory 476079104


 97%|█████████▋| 59/61 [1:13:56<00:21, 10.76s/it]

torch.Size([4, 15, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 390806528
cuda memory 420001792
cuda memory 449721344


 98%|█████████▊| 60/61 [1:14:04<00:09,  9.67s/it]

torch.Size([4, 12, 97])
cuda memory 358729728
cuda memory 358729728
cuda memory 382637568
cuda memory 406561792
cuda memory 430486016


100%|██████████| 61/61 [1:14:09<00:00,  8.46s/it]

torch.Size([4, 9, 97])
cuda memory 358729728



  0%|          | 0/61 [00:00<?, ?it/s]

Train loss for epoch: 5.4342427253723145

Epoch6
cuda memory 358729728
cuda memory 3502744064
cuda memory 6334466560
cuda memory 9160581632
torch.Size([4, 1192, 97])


  2%|▏         | 1/61 [03:57<3:57:49, 237.82s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 3060695040
cuda memory 5759252480
cuda memory 8454950912
torch.Size([4, 1025, 97])


  3%|▎         | 2/61 [10:05<4:32:14, 276.86s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2816188416
cuda memory 5270014976
cuda memory 7705764864
torch.Size([4, 932, 97])


  5%|▍         | 3/61 [15:00<4:32:48, 282.22s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2589237248
cuda memory 4790671360
cuda memory 6992547840
torch.Size([4, 846, 97])


  7%|▋         | 4/61 [18:06<4:00:33, 253.23s/it]

cuda memory 358729728
cuda memory 358729728
cuda memory 2506039296
cuda memory 4533794816
cuda memory 6445551616
torch.Size([4, 809, 97])


  8%|▊         | 5/61 [20:30<3:25:46, 220.47s/it]

cuda memory 358729728
cuda memory 358729728


In [0]:
####################

# Test


In [10]:
model = LSTMTSearch()
# model = LSTMTSearch(hidden_size=128, batch_size=1)
model.load_state_dict(torch.load('/content/drive/My Drive/CSE 527/Project/model7.v5.fltr.drp.h5'))
model.eval()

LSTMTSearch(
  (encoder): Sequential(
    (0): ResNet(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): BasicBlock(
          (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): BasicBlock(
          (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn1): BatchNor

In [0]:
import glob, os
os.chdir("/content/drive/My Drive/CSE 527/Project/1fps/ava/test_videos")
test_ids = []
for file in glob.glob("*.mp4"):
    test_ids.append(file[:-4])

In [0]:
df_test = pd.read_csv(r"/content/drive/My Drive/CSE 527/Project/1fps/ava/ava_test_v1.0.csv",names=['video_id','middle_frame_timestamp', 'x1','y1','x2','y2', 'action_id'], header=None)

In [0]:
df_test_dr_valid = df_test.loc[((df_test['action_id'] == 27) & (df_test['video_id'].isin(test_ids)))]

In [0]:
MIN = 904
MAX = 1798

In [0]:
video_ids = df_test_dr_valid['video_id'].unique()

In [22]:
video_ids

array(['7YpF6DntOYw', 'BCiuXAuCKAU', 'HKjR70GCRPE', 'IzvOYVMltkI',
       'LgBQlW6OTr0', 'P60OxWahxBQ', 'g1wyIcLPbq0', 'kMy-6RtoOVU',
       'yn9WN9lsHRE', 'z-fsLpGHq6o', 'zR725veL-DI'], dtype=object)

In [0]:
def get_next_guess(cap, guess_time, hidden):
    
    cap.set(cv2.CAP_PROP_POS_MSEC,guess_time*1000) 
    ret, frame = cap.read()
    
    train_transforms = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize(70),
    transforms.CenterCrop(64),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
  
    frame2 = train_transforms(frame).cuda()
    frame2.requires_grad=False

    frame3 = frame2.unsqueeze(0)
    activations = model.encoder(frame3).cpu()
    # print(activations.shape)
    
    wrap = torch.from_numpy(numpy.array([[guess_time]], dtype = 'float32'))

    padded_activations = torch.cat((activations, wrap), dim = 1)
    # print(padded_activations.shape)

    batch_ip = padded_activations.unsqueeze(0)
    # print(batch_ip.shape)

    model.lstm.hidden = hidden
    output, (h_n, c_n) = model.lstm(batch_ip)
    # print(output.shape)

    preds = model.linear(output)
    print(preds)
        
    return (h_n, c_n), guess_time + preds.data.item()

In [0]:
import random

def find_action(dataf, video, hidden_states) :    
    
    search_num = 1
    guess_time = random.randint(MIN, MAX)
    
    cap = cv2.VideoCapture('/content/drive/My Drive/CSE 527/Project/1fps/ava/test_videos/'+video+'.mp4')

    for i in range(500) :
        a_g = np.rint(guess_time)
        print(a_g)
        if a_g in dataf:
            break;
        if (a_g - 1 in dataf) & (guess_time + 2 in dataf):
            break;
        if (a_g - 2 in dataf) & (guess_time + 1 in dataf):
            break;
        else :
            search_num = search_num + 1
        if (a_g <= MIN or a_g >= MAX):
            return -1
        
        hidden_states, guess_time = get_next_guess(cap, guess_time, hidden_states)
        if (guess_time == -1):
            return 500
    
    return search_num

In [32]:
total = 0
ct = 0
for i in range(100) : 
    print('epoch', i)
    for video_id in video_ids:
        print(video_id)
        tss = df_test_dr_valid.loc[(df_test_dr_valid['video_id'] == video_id)]['middle_frame_timestamp'].to_list()
        print(tss)

        as_metric = 500
        while (as_metric == 500) :
            as_metric = find_action(tss, video_id, model.get_init_hidden_states())

        total = total + as_metric
        ct = ct + 1
#         print('avg', total/ct)
print('avg', total/ct)

epoch 0
7YpF6DntOYw
[1117, 1117, 1120, 1120, 1192, 1195, 1198, 1201]
975.0
tensor([[[0.1313]]], grad_fn=<AddBackward0>)
975.0
tensor([[[0.1288]]], grad_fn=<AddBackward0>)
975.0
tensor([[[0.1394]]], grad_fn=<AddBackward0>)
975.0
tensor([[[0.1415]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.1445]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.1450]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.1436]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.1380]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0654]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0659]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0430]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0687]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0611]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0836]]], grad_fn=<AddBackward0>)
976.0
tensor([[[0.0967]]], grad_fn=<AddBackward0>)
977.0
tensor([[[0.1249]]], grad_fn=<AddBackward0>)
977.0
tensor([[[0.1283]]], grad_fn=<AddBackward0>)
977.0
tensor([[[0.1070]]], grad_fn=<AddBackward0>)
977.0
tensor(

KeyboardInterrupt: ignored